paths:
  .github/workflows/*.yml:
    ignore:
      # actionlint does not support GitHub's self-repository syntax yet. See
      # https://github.com/rhysd/actionlint/issues/711
      - 'specifying action "\$/[^"]+" in invalid format because ref is missing'
